# coding: utf-8

"""
    Intrinio API

    Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://docs.intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.  # noqa: E501

    OpenAPI spec version: 2.124.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AccountCurrentUsage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_code': 'str',
        'restriction': 'str',
        'count': 'str',
        'limit': 'str',
        'seconds_until_reset': 'str',
        'percentage_used': 'str'
    }

    attribute_map = {
        'access_code': 'access_code',
        'restriction': 'restriction',
        'count': 'count',
        'limit': 'limit',
        'seconds_until_reset': 'seconds_until_reset',
        'percentage_used': 'percentage_used'
    }

    def __init__(self, access_code=None, restriction=None, count=None, limit=None, seconds_until_reset=None, percentage_used=None):  # noqa: E501
        """AccountCurrentUsage - a model defined in Swagger"""  # noqa: E501

        self._access_code = None
        self._restriction = None
        self._count = None
        self._limit = None
        self._seconds_until_reset = None
        self._percentage_used = None
        self.discriminator = None

        if access_code is not None:
            self.access_code = access_code
        if restriction is not None:
            self.restriction = restriction
        if count is not None:
            self.count = count
        if limit is not None:
            self.limit = limit
        if seconds_until_reset is not None:
            self.seconds_until_reset = seconds_until_reset
        if percentage_used is not None:
            self.percentage_used = percentage_used

    @property
    def access_code(self):
        """Gets the access_code of this AccountCurrentUsage.  # noqa: E501

        The access code.  # noqa: E501

        :return: The access_code of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """
        return self._access_code
        
    @property
    def access_code_dict(self):
        """Gets the access_code of this AccountCurrentUsage.  # noqa: E501

        The access code. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The access_code of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """

        result = None

        value = self.access_code
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'access_code': value }

        
        return result
        

    @access_code.setter
    def access_code(self, access_code):
        """Sets the access_code of this AccountCurrentUsage.

        The access code.  # noqa: E501

        :param access_code: The access_code of this AccountCurrentUsage.  # noqa: E501
        :type: str
        """

        self._access_code = access_code

    @property
    def restriction(self):
        """Gets the restriction of this AccountCurrentUsage.  # noqa: E501

        Restrictions on this access code.  # noqa: E501

        :return: The restriction of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """
        return self._restriction
        
    @property
    def restriction_dict(self):
        """Gets the restriction of this AccountCurrentUsage.  # noqa: E501

        Restrictions on this access code. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The restriction of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """

        result = None

        value = self.restriction
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'restriction': value }

        
        return result
        

    @restriction.setter
    def restriction(self, restriction):
        """Sets the restriction of this AccountCurrentUsage.

        Restrictions on this access code.  # noqa: E501

        :param restriction: The restriction of this AccountCurrentUsage.  # noqa: E501
        :type: str
        """

        self._restriction = restriction

    @property
    def count(self):
        """Gets the count of this AccountCurrentUsage.  # noqa: E501

        The current count of API calls using this access code for this period.  # noqa: E501

        :return: The count of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """
        return self._count
        
    @property
    def count_dict(self):
        """Gets the count of this AccountCurrentUsage.  # noqa: E501

        The current count of API calls using this access code for this period. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The count of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """

        result = None

        value = self.count
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'count': value }

        
        return result
        

    @count.setter
    def count(self, count):
        """Sets the count of this AccountCurrentUsage.

        The current count of API calls using this access code for this period.  # noqa: E501

        :param count: The count of this AccountCurrentUsage.  # noqa: E501
        :type: str
        """

        self._count = count

    @property
    def limit(self):
        """Gets the limit of this AccountCurrentUsage.  # noqa: E501

        The limit for this access code  # noqa: E501

        :return: The limit of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """
        return self._limit
        
    @property
    def limit_dict(self):
        """Gets the limit of this AccountCurrentUsage.  # noqa: E501

        The limit for this access code as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The limit of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """

        result = None

        value = self.limit
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'limit': value }

        
        return result
        

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this AccountCurrentUsage.

        The limit for this access code  # noqa: E501

        :param limit: The limit of this AccountCurrentUsage.  # noqa: E501
        :type: str
        """

        self._limit = limit

    @property
    def seconds_until_reset(self):
        """Gets the seconds_until_reset of this AccountCurrentUsage.  # noqa: E501

        The period in seconds for count reset.  # noqa: E501

        :return: The seconds_until_reset of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """
        return self._seconds_until_reset
        
    @property
    def seconds_until_reset_dict(self):
        """Gets the seconds_until_reset of this AccountCurrentUsage.  # noqa: E501

        The period in seconds for count reset. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The seconds_until_reset of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """

        result = None

        value = self.seconds_until_reset
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'seconds_until_reset': value }

        
        return result
        

    @seconds_until_reset.setter
    def seconds_until_reset(self, seconds_until_reset):
        """Sets the seconds_until_reset of this AccountCurrentUsage.

        The period in seconds for count reset.  # noqa: E501

        :param seconds_until_reset: The seconds_until_reset of this AccountCurrentUsage.  # noqa: E501
        :type: str
        """

        self._seconds_until_reset = seconds_until_reset

    @property
    def percentage_used(self):
        """Gets the percentage_used of this AccountCurrentUsage.  # noqa: E501

        The percentage of limit used.  # noqa: E501

        :return: The percentage_used of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """
        return self._percentage_used
        
    @property
    def percentage_used_dict(self):
        """Gets the percentage_used of this AccountCurrentUsage.  # noqa: E501

        The percentage of limit used. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The percentage_used of this AccountCurrentUsage.  # noqa: E501
        :rtype: str
        """

        result = None

        value = self.percentage_used
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'percentage_used': value }

        
        return result
        

    @percentage_used.setter
    def percentage_used(self, percentage_used):
        """Sets the percentage_used of this AccountCurrentUsage.

        The percentage of limit used.  # noqa: E501

        :param percentage_used: The percentage_used of this AccountCurrentUsage.  # noqa: E501
        :type: str
        """

        self._percentage_used = percentage_used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountCurrentUsage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
