# coding: utf-8

"""
    Intrinio API

    Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://docs.intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.  # noqa: E501

    OpenAPI spec version: 2.135.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OptionSurfaceDatum(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'strike_price': 'float',
        'unix_timestamp': 'float',
        'forward_natural_log_moneyness': 'float',
        'square_root_tau': 'float',
        'implied_volatility': 'float'
    }

    attribute_map = {
        'strike_price': 'strike_price',
        'unix_timestamp': 'unix_timestamp',
        'forward_natural_log_moneyness': 'forward_natural_log_moneyness',
        'square_root_tau': 'square_root_tau',
        'implied_volatility': 'implied_volatility'
    }

    def __init__(self, strike_price=None, unix_timestamp=None, forward_natural_log_moneyness=None, square_root_tau=None, implied_volatility=None):  # noqa: E501
        """OptionSurfaceDatum - a model defined in Swagger"""  # noqa: E501

        self._strike_price = None
        self._unix_timestamp = None
        self._forward_natural_log_moneyness = None
        self._square_root_tau = None
        self._implied_volatility = None
        self.discriminator = None

        if strike_price is not None:
            self.strike_price = strike_price
        if unix_timestamp is not None:
            self.unix_timestamp = unix_timestamp
        if forward_natural_log_moneyness is not None:
            self.forward_natural_log_moneyness = forward_natural_log_moneyness
        if square_root_tau is not None:
            self.square_root_tau = square_root_tau
        if implied_volatility is not None:
            self.implied_volatility = implied_volatility

    @property
    def strike_price(self):
        """Gets the strike_price of this OptionSurfaceDatum.  # noqa: E501

        The actual strike price.  Present when the requesting surface type is raw.  # noqa: E501

        :return: The strike_price of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """
        return self._strike_price
        
    @property
    def strike_price_dict(self):
        """Gets the strike_price of this OptionSurfaceDatum.  # noqa: E501

        The actual strike price.  Present when the requesting surface type is raw. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The strike_price of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """

        result = None

        value = self.strike_price
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'strike_price': value }

        
        return result
        

    @strike_price.setter
    def strike_price(self, strike_price):
        """Sets the strike_price of this OptionSurfaceDatum.

        The actual strike price.  Present when the requesting surface type is raw.  # noqa: E501

        :param strike_price: The strike_price of this OptionSurfaceDatum.  # noqa: E501
        :type: float
        """

        self._strike_price = strike_price

    @property
    def unix_timestamp(self):
        """Gets the unix_timestamp of this OptionSurfaceDatum.  # noqa: E501

        The expiration DateTime.  Present when the requesting surface type is raw.  # noqa: E501

        :return: The unix_timestamp of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """
        return self._unix_timestamp
        
    @property
    def unix_timestamp_dict(self):
        """Gets the unix_timestamp of this OptionSurfaceDatum.  # noqa: E501

        The expiration DateTime.  Present when the requesting surface type is raw. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The unix_timestamp of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """

        result = None

        value = self.unix_timestamp
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'unix_timestamp': value }

        
        return result
        

    @unix_timestamp.setter
    def unix_timestamp(self, unix_timestamp):
        """Sets the unix_timestamp of this OptionSurfaceDatum.

        The expiration DateTime.  Present when the requesting surface type is raw.  # noqa: E501

        :param unix_timestamp: The unix_timestamp of this OptionSurfaceDatum.  # noqa: E501
        :type: float
        """

        self._unix_timestamp = unix_timestamp

    @property
    def forward_natural_log_moneyness(self):
        """Gets the forward_natural_log_moneyness of this OptionSurfaceDatum.  # noqa: E501

        The natural logarithm of forward moneyness, calculated as ln(F / K), where F is the forward underlying price adjusted for risk-free rate and dividend yield over time to expiration, and K is the option strike. Present when the requesting surface type is something other than raw.  # noqa: E501

        :return: The forward_natural_log_moneyness of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """
        return self._forward_natural_log_moneyness
        
    @property
    def forward_natural_log_moneyness_dict(self):
        """Gets the forward_natural_log_moneyness of this OptionSurfaceDatum.  # noqa: E501

        The natural logarithm of forward moneyness, calculated as ln(F / K), where F is the forward underlying price adjusted for risk-free rate and dividend yield over time to expiration, and K is the option strike. Present when the requesting surface type is something other than raw. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The forward_natural_log_moneyness of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """

        result = None

        value = self.forward_natural_log_moneyness
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'forward_natural_log_moneyness': value }

        
        return result
        

    @forward_natural_log_moneyness.setter
    def forward_natural_log_moneyness(self, forward_natural_log_moneyness):
        """Sets the forward_natural_log_moneyness of this OptionSurfaceDatum.

        The natural logarithm of forward moneyness, calculated as ln(F / K), where F is the forward underlying price adjusted for risk-free rate and dividend yield over time to expiration, and K is the option strike. Present when the requesting surface type is something other than raw.  # noqa: E501

        :param forward_natural_log_moneyness: The forward_natural_log_moneyness of this OptionSurfaceDatum.  # noqa: E501
        :type: float
        """

        self._forward_natural_log_moneyness = forward_natural_log_moneyness

    @property
    def square_root_tau(self):
        """Gets the square_root_tau of this OptionSurfaceDatum.  # noqa: E501

        The square root of tau, where tau is the option’s time to expiration in years using a 365.25-day year basis. Present when the requesting surface type is something other than raw.  # noqa: E501

        :return: The square_root_tau of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """
        return self._square_root_tau
        
    @property
    def square_root_tau_dict(self):
        """Gets the square_root_tau of this OptionSurfaceDatum.  # noqa: E501

        The square root of tau, where tau is the option’s time to expiration in years using a 365.25-day year basis. Present when the requesting surface type is something other than raw. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The square_root_tau of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """

        result = None

        value = self.square_root_tau
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'square_root_tau': value }

        
        return result
        

    @square_root_tau.setter
    def square_root_tau(self, square_root_tau):
        """Sets the square_root_tau of this OptionSurfaceDatum.

        The square root of tau, where tau is the option’s time to expiration in years using a 365.25-day year basis. Present when the requesting surface type is something other than raw.  # noqa: E501

        :param square_root_tau: The square_root_tau of this OptionSurfaceDatum.  # noqa: E501
        :type: float
        """

        self._square_root_tau = square_root_tau

    @property
    def implied_volatility(self):
        """Gets the implied_volatility of this OptionSurfaceDatum.  # noqa: E501

        The implied volatility of the contract calculated using the Black-Scholes Model, and smoothed if the requesting surface type was logarithmic_smoothed. Always present.  # noqa: E501

        :return: The implied_volatility of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """
        return self._implied_volatility
        
    @property
    def implied_volatility_dict(self):
        """Gets the implied_volatility of this OptionSurfaceDatum.  # noqa: E501

        The implied volatility of the contract calculated using the Black-Scholes Model, and smoothed if the requesting surface type was logarithmic_smoothed. Always present. as a dictionary. Useful for Panda Dataframes.  # noqa: E501

        :return: The implied_volatility of this OptionSurfaceDatum.  # noqa: E501
        :rtype: float
        """

        result = None

        value = self.implied_volatility
        if isinstance(value, list):
            result = list(map(
                lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                value
            ))
        elif hasattr(value, "to_dict"):
            result = value.to_dict()
        elif isinstance(value, dict):
            result = dict(map(
                lambda item: (item[0], item[1].to_dict())
                if hasattr(item[1], "to_dict") else item,
                value.items()
            ))
        else:
            result = { 'implied_volatility': value }

        
        return result
        

    @implied_volatility.setter
    def implied_volatility(self, implied_volatility):
        """Sets the implied_volatility of this OptionSurfaceDatum.

        The implied volatility of the contract calculated using the Black-Scholes Model, and smoothed if the requesting surface type was logarithmic_smoothed. Always present.  # noqa: E501

        :param implied_volatility: The implied_volatility of this OptionSurfaceDatum.  # noqa: E501
        :type: float
        """

        self._implied_volatility = implied_volatility

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OptionSurfaceDatum):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
